########################### NETWORKS
networks:
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24
  traefik_proxy:
    name: traefik_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24

########################### SECRETS
secrets:
  basic_auth_credentials:
    file: $DOCKERDIR/secrets/basic_auth_credentials
  cf_dns_api_token:
    file: $DOCKERDIR/secrets/cf_dns_api_token
  authelia_jwt_secret:
    file: $DOCKERDIR/secrets/authelia_jwt_secret
  authelia_session_secret:
    file: $DOCKERDIR/secrets/authelia_session_secret
  authelia_storage_encryption_key:
    file: $DOCKERDIR/secrets/authelia_storage_encryption_key

include:
  ########################### SERVICES
  # HOSTNAME=pegasus - defined in .env

  # CORE
  - compose/$HOSTNAME/adguard.yaml
  - compose/$HOSTNAME/authelia.yaml
  - compose/$HOSTNAME/socket-proxy.yaml
  - compose/$HOSTNAME/tailscale.yaml
  - compose/$HOSTNAME/traefik.yaml
  - compose/$HOSTNAME/watchtower.yaml
  - compose/$HOSTNAME/portainer.yaml

  # APPS
  - compose/$HOSTNAME/chat.yaml
  - compose/$HOSTNAME/cf_ddns.yaml
  - compose/$HOSTNAME/dozzle.yaml
  - compose/$HOSTNAME/gpt.yaml
  - compose/$HOSTNAME/home-assistant.yaml
  - compose/$HOSTNAME/immich.yaml
  - compose/$HOSTNAME/jellystat.yaml # need to merge into media server
  - compose/$HOSTNAME/media_server.yaml
  - compose/$HOSTNAME/motioneye.yaml
  - compose/$HOSTNAME/mvsa.yaml
  - compose/$HOSTNAME/nextcloud.yaml
  - compose/$HOSTNAME/octoprint.yaml
  - compose/$HOSTNAME/pastefy.yaml
  - compose/$HOSTNAME/your-spotify.yaml
  - compose/$HOSTNAME/jira.yaml
  - compose/$HOSTNAME/pdf.yaml
  - compose/$HOSTNAME/obsidian.yaml
  - compose/$HOSTNAME/github-readme.yaml
  - compose/$HOSTNAME/files.yaml
    #  - compose/$HOSTNAME/lynx.yaml
    # - compose/$HOSTNAME/windows.yaml
  # BOTS
  - compose/$HOSTNAME/volleybot.yaml
  - compose/$HOSTNAME/crodiebot.yaml

  # TODO
  # money, monitoring, watchtower?
