http:
  middlewares:
    amp-middlewares-headers:
      headers:
        customRequestHeaders:
          X-AMP-Scheme: "https"
        customResponseHeaders:
          X-Proxy-Buffering: "off"
          Content-Security-Policy: "frame-ancestors 'self' https://organizr.ashpanraskar.com;"

    #     accessControlMaxAge: 100
    #     hostsProxyHeaders:
    #       - "X-Forwarded-Host"
    #     stsSeconds: 63072000
    #     stsIncludeSubdomains: true
    #     stsPreload: true
    #     # forceSTSHeader: true # This is a good thing but it can be tricky. Enable after everything works.
    #     customFrameOptionsValue: SAMEORIGIN # https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
    #     contentTypeNosniff: true
    #     browserXssFilter: true
    #     referrerPolicy: "same-origin"
    #     permissionsPolicy: "camera=(), microphone=(), geolocation=(), payment=(), usb=(), vr=()"
    #     customResponseHeaders:
    #       X-Robots-Tag: "none" # disable search engines from indexing home server
    #       server: "" # hide server info from visitors
    # nextcloud-redirect:
    #   redirectRegex:
    #     permanent: true
    #     regex: "https://(.*)/.well-known/(card|cal)dav"
    #     replacement: "https://${1}/remote.php/dav/"
