services:
  nextcloud:
    container_name: nextcloud-aio-mastercontainer
    image: nextcloud/all-in-one:latest
    restart: always
    ports:
      # - 16000:80
      - 16001:8080
      # - 16002:8443
    environment:
      - APACHE_PORT=11000
      - NEXTCLOUD_DATADIR=$NEXTCLOUD_DATADIR
      # - NEXTCLOUD_MOUNT=$NEXTCLOUD_DATADIR
      - DOCKER_HOST=tcp://socket-proxy:2375
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # network_mode: host
    # networks:
    #   - traefik_proxy
    #   - socket_proxy
volumes:
  # If you want to store the data on a different drive, see https://github.com/nextcloud/all-in-one#how-to-store-the-filesinstallation-on-a-separate-drive
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed as otherwise the built-in backup solution will not work
