services:
  server:
    container_name: your_spotify_server
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8088:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: ${API_ENDPOINT}
      CLIENT_ENDPOINT: ${CLIENT_ENDPOINT}
      SPOTIFY_PUBLIC: ${SPOTIFY_PUBLIC}
      SPOTIFY_SECRET: ${SPOTIFY_SECRET}
      CORS: i-want-a-security-vulnerability-and-want-to-allow-all-origins
  mongo:
    container_name: mongo
    image: mongo:6
    volumes:
      - ./config/db:/data/db

  web:
    container_name: your_spotify_client
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3001:3000"
    environment:
      API_ENDPOINT: ${API_ENDPOINT}
