services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome
    restart: unless-stopped
    ports:
      - 53:53/tcp # plain dns over tcp
      - 53:53/udp # plain dns over udp
      - 3006:80/tcp # http web interface
      - 3005:3000/tcp # initial setup web interface
    volumes:
      - ./config/work:/opt/adguardhome/work
      - ./config/conf:/opt/adguardhome/conf
